#ifndef BOOST_MP11_DETAIL_MODULES_HPP_INCLUDED
#define BOOST_MP11_DETAIL_MODULES_HPP_INCLUDED

#ifdef BOOST_USE_MODULES
#define BOOST_MODULE_EXPORT export
#else
#define BOOST_MODULE_EXPORT
#endif

#endif