////
Copyright 2017 Peter Dimov

Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

[#list]
# List Operations, <boost/mp11/list.hpp>
:toc:
:toc-title:
:idprefix:

## mp_list<T...>

    template<class... T> struct mp_list {};

`mp_list` is the standard list type of Mp11, although the library is not restricted to it and can operate on arbitrary class templates
such as `std::tuple` or `std::variant`. Even `std::pair` can be used if the transformation does not alter the number of the elements in
the list.

## mp_size<L>

    template<class L> using mp_size = /*...*/;

`mp_size<L>` returns the number of elements in the list `L`, as a `mp_size_t`. In other words, `mp_size<L<T...>>` is an alias for
`mp_size_t<sizeof...(T)>`.

Examples:

    using L1 = mp_list<>;
    using R1 = mp_size<L1>; // mp_size_t\<0>

    using L2 = std::pair<int, int>;
    using R2 = mp_size<L2>; // mp_size_t\<2>

    using L3 = std::tuple<float>;
    using R3 = mp_size<L3>; // mp_size_t\<1>

## mp_empty<L>

    template<class L> using mp_empty = mp_bool<mp_size<L>::value == 0>;

`mp_empty<L>` is an alias for `mp_true` if the list `L` is empty, for `mp_false` otherwise.

## mp_front<L>

    template<class L> using mp_front = /*...*/;

`mp_front<L>` is the first element of the list `L`. That is, `mp_front<L<T1, T...>>` is an alias for `T1`.

Examples:

    using L1 = std::pair<int, float>;
    using R1 = mp_front<L1>; // int

    using L2 = std::tuple<float, double, long double>;
    using R2 = mp_front<L2>; // float

    using L3 = mp_list<char[1], char[2], char[3], char[4]>;
    using R3 = mp_front<L3>; // char[1]

## mp_pop_front<L>

    template<class L> using mp_pop_front = /*...*/;

`mp_pop_front<L>` removes the first element of the list `L`. That is, `mp_pop_front<L<T1, T...>>` is an alias for `L<T...>`.

Examples:

    using L1 = std::tuple<float, double, long double>;
    using R1 = mp_pop_front<L1>; // std::tuple<double, long double>

    using L2 = mp_list<void>;
    using R2 = mp_pop_front<L2>; // mp_list<>

## mp_first<L>

    template<class L> using mp_first = mp_front<L>;

`mp_first` is another name for `mp_front`.

## mp_rest<L>

    template<class L> using mp_rest = mp_pop_front<L>;

`mp_rest` is another name for `mp_pop_front`.

## mp_second<L>

    template<class L> using mp_second = /*...*/;

`mp_second<L>` is the second element of the list `L`. That is, `mp_second<L<T1, T2, T...>>` is an alias for `T2`.

Examples:

    using L1 = std::pair<int, float>;
    using R1 = mp_second<L1>; // float

    using L2 = std::tuple<float, double, long double>;
    using R2 = mp_second<L2>; // double

    using L3 = mp_list<char[1], char[2], char[3], char[4]>;
    using R3 = mp_second<L3>; // char[2]

## mp_third<L>

    template<class L> using mp_third = /*...*/;

`mp_third<L>` is the third element of the list `L`. That is, `mp_third<L<T1, T2, T3, T...>>` is an alias for `T3`.

Examples:

    using L1 = std::tuple<float, double, long double>;
    using R1 = mp_third<L1>; // long double

    using L2 = mp_list<char[1], char[2], char[3], char[4]>;
    using R2 = mp_third<L2>; // char[3]

## mp_push_front<L, T...>

    template<class L, class... T> using mp_push_front = /*...*/;

`mp_push_front<L, T...>` inserts the elements `T...` at the front of the list `L`. That is, `mp_push_front<L<U...>, T...>`
is an alias for `L<T..., U...>`.

Examples:

    using L1 = std::tuple<double, long double>;
    using R1 = mp_push_front<L1, float>; // std::tuple<float, double, long double>

    using L2 = mp_list<void>;
    using R2 = mp_push_front<L2, char[1], char[2]>; // mp_list<char[1], char[2], void>

## mp_push_back<L, T...>

    template<class L, class... T> using mp_push_back = /*...*/;

`mp_push_back<L, T...>` inserts the elements `T...` at the back of the list `L`. That is, `mp_push_back<L<U...>, T...>`
is an alias for `L<U..., T...>`.

Examples:

    using L1 = std::tuple<double, long double>;
    using R1 = mp_push_back<L1, float>; // std::tuple<double, long double, float>

    using L2 = mp_list<void>;
    using R2 = mp_push_back<L2, char[1], char[2]>; // mp_list<void, char[1], char[2]>

## mp_rename<L, Y>

    template<class L, template<class...> class Y> using mp_rename = /*...*/;

`mp_rename<L, Y>` changes the type of the list `L` to `Y`. That is, `mp_rename<L<T...>, Y>` is an alias for `Y<T...>`.

Examples:

    using L1 = std::pair<double, long double>;
    using R1 = mp_rename<L1, std::tuple>; // std::tuple<double, long double>

    using L2 = std::tuple<void>;
    using R2 = mp_rename<L2, mp_list>; // mp_list<void>

## mp_apply<F, L>

    template<template<class...> class F, class L> using mp_apply = mp_rename<L, F>;

`mp_apply<F, L>` applies the metafunction `F` to the contents of the list `L`, that is, `mp_apply<F, L<T...>>` is an alias for `F<T...>`.
(`mp_apply` is the same as `mp_rename` with the arguments reversed.)

Example:

    using L1 = std::pair<double, long double>;
    using R1 = mp_apply<std::is_same, L1>; // std::is_same<double, long double>

## mp_apply_q<Q, L>

    template<class Q, class L> using mp_apply_q = mp_apply<Q::template fn, L>;

Same as `mp_apply`, but takes a quoted metafunction.

Example:

```
using L1 = std::tuple<double, long double>;
using L2 = mp_list<int, long>;

using R1 = mp_apply_q<mp_bind_front<mp_push_back, L1>, L2>;
// R1 is std::tuple<double, long double, int, long>
```

## mp_append<L...>

    template<class... L> using mp_append = /*...*/;

`mp_append<L...>` concatenates the lists in `L...` into a single list that has the same type as the first list. `mp_append<>`
is an alias for `mp_list<>`. `mp_append<L1<T1...>, L2<T2...>, ..., Ln<Tn...>>` is an alias for `L1<T1..., T2..., ..., Tn...>`.

Example:

```
using L1 = std::tuple<double, long double>;
using L2 = mp_list<int>;
using L3 = std::pair<short, long>;
using L4 = mp_list<>;

using R1 = mp_append<L1, L2, L3, L4>; // std::tuple<double, long double, int, short, long>
```

## mp_replace_front<L, T>

    template<class L, class T> using mp_replace_front = /*...*/;

`mp_replace_front<L, T>` replaces the first element of the list `L` with `T`. That is, `mp_replace_front<L<U1, U...>, T>` is
an alias for `L<T, U...>`.

Examples:

    using L1 = std::pair<int, float>;
    using R1 = mp_replace_front<L1, void>; // std::pair<void, float>

    using L2 = std::tuple<float, double, long double>;
    using R2 = mp_replace_front<L2, void>; // std::tuple<void, double, long double>

    using L3 = mp_list<char[1], char[2], char[3], char[4]>;
    using R3 = mp_replace_front<L3, void>; // mp_list<void, char[2], char[3], char[4]>;

## mp_replace_first<L, T>

    template<class L, class T> using mp_replace_first = mp_replace_front<L, T>;

`mp_replace_first` is another name for `mp_replace_front`.

## mp_replace_second<L, T>

    template<class L, class T> using mp_replace_second = /*...*/;

`mp_replace_second<L, T>` replaces the second element of the list `L` with `T`. That is, `mp_replace_second<L<U1, U2, U...>, T>`
is an alias for `L<U1, T, U...>`.

Examples:

    using L1 = std::pair<int, float>;
    using R1 = mp_replace_second<L1, void>; // std::pair<int, void>

    using L2 = std::tuple<float, double, long double>;
    using R2 = mp_replace_second<L2, void>; // std::tuple<float, void, long double>

    using L3 = mp_list<char[1], char[2], char[3], char[4]>;
    using R3 = mp_replace_second<L3, void>; // mp_list<char[1], void, char[3], char[4]>;

## mp_replace_third<L, T>

    template<class L, class T> using mp_replace_third = /*...*/;

`mp_replace_third<L, T>` replaces the third element of the list `L` with `T`. That is, `mp_replace_third<L<U1, U2, U3, U...>, T>`
is an alias for `L<U1, U2, T, U...>`.

Examples:

    using L1 = std::tuple<float, double, long double>;
    using R1 = mp_replace_third<L1, void>; // std::tuple<float, double, void>

    using L2 = mp_list<char[1], char[2], char[3], char[4]>;
    using R2 = mp_replace_third<L2, void>; // mp_list<char[1], char[2], void, char[4]>;
